MODULE TIMING_MOD

CONTAINS

FUNCTION GET_TIME

USE ISO_FORTRAN_ENV, ONLY: INT64, REAL64

IMPLICIT NONE

INTEGER(INT64) :: COUNT
REAL(REAL64) :: COUNT_RATE
REAL(REAL64) :: GET_TIME

CALL SYSTEM_CLOCK(COUNT, COUNT_RATE=COUNT_RATE)

GET_TIME = REAL(COUNT, REAL64) / COUNT_RATE

END FUNCTION GET_TIME

END MODULE TIMING_MOD
