MODULE TIMING_MOD

USE EC_PARKIND, ONLY: JPRD

REAL(JPRD), PUBLIC, ALLOCATABLE :: T_EVENT(:)
INTEGER, PUBLIC, ALLOCATABLE :: T_TYPE(:), T_BATCH(:), T_STAGE(:)
INTEGER, PUBLIC :: TCOUNT
INTEGER, PUBLIC, PARAMETER :: TCOMM1 = 1
INTEGER, PUBLIC, PARAMETER :: TCOMM2 = 2
INTEGER, PUBLIC, PARAMETER :: TCOMM3 = 3
INTEGER, PUBLIC, PARAMETER :: TCOMP1 = 4
INTEGER, PUBLIC, PARAMETER :: TCOMP2 = 5

CONTAINS

FUNCTION GET_TIME

USE MPI, ONLY: MPI_WTIME

IMPLICIT NONE

REAL(JPRD) :: GET_TIME

GET_TIME = MPI_WTIME()

END FUNCTION GET_TIME

END MODULE TIMING_MOD
